#!/bin/bash -e

name="$1"

source __validation
validate_repo_name "$name"
check_no_repo "$name"

repo_dir="${ROOT_DIR}/repos/${name}"

mkdir "$repo_dir" --mode 775
sudo chown "${OWNER_USER}:${ADMIN_GRP}" "$repo_dir"
git -C "$repo_dir" init
