#!/bin/bash -e

login="$1"

source __validation
validate_login "$login"
check_is_admin "$login"

cd "${ROOT_DIR}/users/${login}"

gpasswd --delete "$login" "$ADMIN_GRP"
rm repos
ln --symbolic _repos repos
