#!/bin/bash -e

login="$1"

source __validation
validate_login "$login"
check_not_admin "$login"

cd "${ROOT_DIR}/users/${login}"

gpasswd --add "$login" "$ADMIN_GRP"
rm repos
ln --symbolic "${ROOT_DIR}/repos" repos
