#!/bin/bash -e

login="$1"
password="$2"

source __validation
validate_login "$login"
check_user_not_exists "$login"

homedir="$USER_DIR"/"$login"

useradd \
    --groups "$USER_GRP" \
    --base-dir "$USER_DIR" \
    --create-home \
    --no-user-group \
    "$login"
chpasswd <<< "$login:$password"
ln -s "$CMD_DIR" "$homedir"/git-shell-commands
mkdir "$homedir"/repos

