#!/bin/bash -e

login="$1"
password="$2"

source __validation
validate_login "$login"
check_user_not_exists "$login"

homedir="${ROOT_DIR}/users/${login}"

sudo useradd \
    --create-home \
    --base-dir "${ROOT_DIR}/users" \
    --skel "${ROOT_DIR}/dir_skel" \
    --no-user-group \
    --groups "$USER_GRP" \
    "$login"
sudo chpasswd <<< "$login:$password"
