#!/bin/bash -e

source __lookup

users="$(find -L "${ROOT_DIR}/users" -mindepth 1 -maxdepth 1 -printf '%f\n' | sort)"

for login in $users; do
    printf '%s %s\n' "$login" "$(get_role "$login")"
done
